### ISSUE TITLE
Next-auth 관련 오류 수정

### ISSUE THREAD

**Issue by DongYounYim** [re-Duck/reDuck-client#71]
1. 프로필 업데이트 시 오류 [next-auth][error][CLIENT_FETCH_ERROR]
=> .env 환경설정에 관련된 오류라고 합니다.

로컬환경기준, .env 파일에 
NEXTAUTH_URL=http://127.0.0.1:3000/
입력하라는 것이 제일 많은데 왜 안되는지 모르겠음.

2. SESSION_ERROR [next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
  message: 'decryption operation failed',
  stack: 'JWEDecryptionFailed: decryption operation failed\n' +
    '    at gcmDecrypt (/Users/younique/Develop/reDuck-client/client/node_modules/jose/dist/node/cjs/runtime/decrypt.js:67:15)\n' +
    '    at decrypt (/Users/younique/Develop/reDuck-client/client/node_modules/jose/dist/node/cjs/runtime/decrypt.js:92:20)\n' +
    '    at flattenedDecrypt (/Users/younique/Develop/reDuck-client/client/node_modules/jose/dist/node/cjs/jwe/flattened/decrypt.js:119:52)\n' +
    '    at async compactDecrypt (/Users/younique/Develop/reDuck-client/client/node_modules/jose/dist/node/cjs/jwe/compact/decrypt.js:18:23)\n' +
    '    at async jwtDecrypt (/Users/younique/Develop/reDuck-client/client/node_modules/jose/dist/node/cjs/jwt/decrypt.js:8:23)\n' +
    '    at async Object.decode (/Users/younique/Develop/reDuck-client/client/node_modules/next-auth/jwt/index.js:64:7)\n' +
    '    at async Object.session (/Users/younique/Develop/reDuck-client/client/node_modules/next-auth/core/routes/session.js:43:28)\n' +
    '    at async AuthHandler (/Users/younique/Develop/reDuck-client/client/node_modules/next-auth/core/index.js:165:27)\n' +
    '    at async NextAuthApiHandler (/Users/younique/Develop/reDuck-client/client/node_modules/next-auth/next/index.js:22:19)\n' +
    '    at async NextAuth._args$ (/Users/younique/Develop/reDuck-client/client/node_modules/next-auth/next/index.js:106:14)\n' +
    '    at async Object.apiResolver (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
    '    at async DevServer.runApi (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/next-server.js:514:9)\n' +
    '    at async Object.fn (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/next-server.js:828:35)\n' +
    '    at async Router.execute (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/router.js:243:32)\n' +
    '    at async DevServer.runImpl (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/base-server.js:432:29)\n' +
    '    at async DevServer.run (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/dev/next-dev-server.js:831:20)\n' +
    '    at async DevServer.handleRequestImpl (/Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/base-server.js:375:20)\n' +
    '    at async /Users/younique/Develop/reDuck-client/client/node_modules/next/dist/server/base-server.js:157:99',
  name: 'JWEDecryptionFailed'
}

**Comment by bae-sh** [comment]
로컬 환경을 실행하고 첫 로그인시에만 뜨는것을 보면 좀 더 알아볼 필요가 있을거 같네요. 배포환경도 확인해 봅시다.
